name: Fourth_workflow

on: 
  workflow_run:
    workflows: [Third_workflow]
    types: 
      - completed

jobs:
  success-command:
    runs-on: ubuntu-latest
    steps:
      - name: List Files
        run: echo "Hello"