name: Tenth_workflow

on: [push] 
 
jobs:
  run-tenth-command:
    runs-on: ubuntu-latest
    environment: "prod"
    steps:
      - name: Our Vars and Secret
        run: |
         echo "${{vars.Status}}"
         echo "${{vars.PASSWORD}}"